'use client'
import {useEffect, useState} from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";
import { usePathname, useRouter } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const router = useRouter();
  let pathname = usePathname();
  let [sessionTemp, sessionAuth] = useState(true);
  let [idVal, idValChk] = useState('');
  let [passVal, passValChk] = useState('');

  const [isLeftVisible, setIsLeftVisible] = useState(false);
  const handleNavIconClick = () => {
    setIsLeftVisible(!isLeftVisible);
  };

  useEffect(() => {
    function clickOutside(e) {
      const qrLeftElement = document.querySelector(".qr-left");
      const qrLogoElement = document.querySelector(".qr-logo");

      if (
        isLeftVisible &&
        !qrLeftElement.contains(e.target) &&
        !qrLogoElement.contains(e.target)
      ) {
        setIsLeftVisible(false);
      }
    }
    document.addEventListener("click", clickOutside);
    return () => {
      document.removeEventListener("click", clickOutside);
    };
  }, [isLeftVisible]);

  function accChk(){
    var passKey = new Object;
    passKey['id'] = 'admin';
    passKey['pass'] = '1234qwer';

    if(idVal == passKey.id && passVal == passKey.pass){
      alert('관리자님 ㅎㅇ');
      sessionAuth(!sessionTemp);
      router.push("/event"); // dashboard 필요시까지 main=>/event로 진행
    } else {
      alert('계정 정보를 다시 확인해주세요');
    }
  }

  return (
    <html lang="ko">
     <body className={isLeftVisible ? 'show-left' : ''}>
        {sessionTemp ? (
          <div className='wrap'>

            {/* qr-logo */}
            <div className='qr-logo'>
              <a href='/event'>
                <span>StempTour</span>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="inline-block w-4 h-4 mb-1"><path fillRule="evenodd" d="M10.868 2.884c-.321-.772-1.415-.772-1.736 0l-1.83 4.401-4.753.381c-.833.067-1.171 1.107-.536 1.651l3.62 3.102-1.106 4.637c-.194.813.691 1.456 1.405 1.02L10 15.591l4.069 2.485c.713.436 1.598-.207 1.404-1.02l-1.106-4.637 3.62-3.102c.635-.544.297-1.584-.536-1.65l-4.752-.382-1.831-4.401z" clipRule="evenodd" /></svg>
                <span className='text-slate-950'>Admin</span>
              </a>
            </div>
            
            {/* qr-left */}
            <div className='qr-left'>
              <label className='qr-left__label' htmlFor=".qr-left__menu">관리 항목</label>
              <ul className="qr-left__menu">
                <li className="qr-left__item">
                  <Link href='/event' className={pathname == '/event'? 'qr-left__link active':'qr-left__link'}>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6 inline-block"><path strokeLinecap="round" strokeLinejoin="round" d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z" /></svg>
                    <span className='qr-left__item__label'>이벤트 관리</span>
                  </Link>
                </li>
                <li className="qr-left__item">
                  <Link href='/user' className={pathname == '/user'? 'qr-left__link active':'qr-left__link'}>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6 inline-block	"><path strokeLinecap="round" strokeLinejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" /></svg>
                    <span className='qr-left__item__label'>사용자</span>
                  </Link>
                </li>
              </ul>
            </div>
            
            {/* qr-header */}
            <div className='qr-header'>
              <div className="qr-header__naviwrap">
                <button className="qr-header__navicon" onClick={handleNavIconClick}>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6 qr-header__navisvg">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 9h16.5m-16.5 6.75h16.5" />
                  </svg>
                </button>
              </div>
            </div>

            {/* qr-right */}
            <div className='qr-right'></div>

            {/* qr-main */}
            <div className='qr-main'>
              <div className="qr-main__pagetitle">
                {pathname == '/event'
                  ?
                  <>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="inline-block"><path strokeLinecap="round" strokeLinejoin="round" d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z" /></svg>
                    <div>
                      <h4>이벤트 관리</h4>
                      <p>이벤트 정보 업데이트, 리소스 할당 등의 작업을 간편하게 수행해 이벤트 진행을 원활하게 조율하세요.</p>
                    </div>
                  </>
                  :
                  ''
                }
                {pathname == '/user'
                  ?
                  <>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1} stroke="currentColor" className="inline-block	"><path strokeLinecap="round" strokeLinejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" /></svg>
                    <div>
                      <h4>사용자</h4>
                      <p>사용자의 가입 상세 정보와 함께 이벤트 참여 기록을 손쉽게 확인하고 분석할 수 있습니다.</p>
                    </div>
                  </>
                  :''
                }
              </div>
              <div className="qr-main__pagebody">
                <div className="qr-main__section-wrapper">
                  {children}
                </div>
              </div>
            </div>
          </div>
          ) : (
            //////////////////////////////////// LOGIN PAGE
            <div className="h-full-vh w-full flex flex-col items-center justify-center bg-slate-100">
              <div className="w-96">
                <div className="bg-white shadow rounded p-10">
                  <p tabIndex={0} role="heading" aria-label="Login to your account" className="text-2xl font-extrabold leading-6 text-gray-800 mb-5">
                    Stemp Tour Admin
                  </p>
                  <div>
                    <lable className="text-sm font-medium leading-none text-gray-800">Accout</lable>
                    <input onChange={(e)=>{ idValChk(e.target.value) }} aria-label="enter email adress" role="input" type="email" className="bg-gray-200 border rounded focus:outline-none text-xs font-medium leading-none text-gray-800 py-3 w-full pl-3 mt-2" />
                  </div>
                  <div className="mt-6  w-full">
                    <lable className="text-sm font-medium leading-none text-gray-800">Password</lable>
                    <div className="relative flex items-center justify-center">
                      <input onChange={(e)=>{ passValChk(e.target.value) }} aria-label="enter Password" role="input" type="password" className="bg-gray-200 border rounded focus:outline-none text-xs font-medium leading-none text-gray-800 py-3 w-full pl-3 mt-2" />
                      <div className="absolute right-0 mt-2 mr-3 cursor-pointer">
                        <svg width={16} height={16} viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <path
                            d="M7.99978 2C11.5944 2 14.5851 4.58667 15.2124 8C14.5858 11.4133 11.5944 14 7.99978 14C4.40511 14 1.41444 11.4133 0.787109 8C1.41378 4.58667 4.40511 2 7.99978 2ZM7.99978 12.6667C9.35942 12.6664 10.6787 12.2045 11.7417 11.3568C12.8047 10.509 13.5484 9.32552 13.8511 8C13.5473 6.67554 12.8031 5.49334 11.7402 4.64668C10.6773 3.80003 9.35864 3.33902 7.99978 3.33902C6.64091 3.33902 5.32224 3.80003 4.25936 4.64668C3.19648 5.49334 2.45229 6.67554 2.14844 8C2.45117 9.32552 3.19489 10.509 4.25787 11.3568C5.32085 12.2045 6.64013 12.6664 7.99978 12.6667ZM7.99978 11C7.20413 11 6.44106 10.6839 5.87846 10.1213C5.31585 9.55871 4.99978 8.79565 4.99978 8C4.99978 7.20435 5.31585 6.44129 5.87846 5.87868C6.44106 5.31607 7.20413 5 7.99978 5C8.79543 5 9.55849 5.31607 10.1211 5.87868C10.6837 6.44129 10.9998 7.20435 10.9998 8C10.9998 8.79565 10.6837 9.55871 10.1211 10.1213C9.55849 10.6839 8.79543 11 7.99978 11ZM7.99978 9.66667C8.4418 9.66667 8.86573 9.49107 9.17829 9.17851C9.49085 8.86595 9.66644 8.44203 9.66644 8C9.66644 7.55797 9.49085 7.13405 9.17829 6.82149C8.86573 6.50893 8.4418 6.33333 7.99978 6.33333C7.55775 6.33333 7.13383 6.50893 6.82126 6.82149C6.5087 7.13405 6.33311 7.55797 6.33311 8C6.33311 8.44203 6.5087 8.86595 6.82126 9.17851C7.13383 9.49107 7.55775 9.66667 7.99978 9.66667Z"
                            fill="#71717A"
                          />
                        </svg>
                      </div>
                    </div>
                  </div>
                  <div className="mt-8">
                    <button role="button" 
                      className="focus:ring-2 focus:ring-offset-2 focus:ring-indigo-700 text-sm font-semibold leading-none text-white focus:outline-none bg-slate-900 border rounded py-4 w-full"
                      onClick={accChk}>
                      Sign in
                    </button>
                  </div>
                </div>
              </div>
            </div>
          )
        }
      </body>
    </html>
  )
}
